from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    """
    Create the layout of the Order Form.
    """

    class Meta:
        """
        Manage the behavior of the model fields.
        """
        model = Order
        fields = (
            'full_name',
            'email',
            'phone_number',
            'country',
            'post_code',
            'town_or_city',
            'address_line1',
            'address_line2',
            'county_or_state',
        )

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove autogenerated labels, and
        set autofocus to the first field.
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'full_name': 'Full Name',
            'email': 'Email Address',
            'phone_number': 'Phone Number',
            'country': 'Country',
            'post_code': 'Postal Code',
            'town_or_city': 'Town or City',
            'address_line1': 'Address Line 1',
            'address_line2': 'Address Line 2 (optional)',
            'county_or_state': 'County / State',
        }

        # Set autofocus on the first field
        self.fields['full_name'].widget.attrs['autofocus'] = True

        for field in self.fields:
            # Add a class to style the form fields with CSS
            self.fields[field].widget.attrs['class'] = 'stripe-style-input'

            # Remove labels from all fields
            self.fields[field].label = False

            # Set placeholders to the fields
            if field in placeholders:
                self.fields[field].widget.attrs['placeholder'] = placeholders[field]

            # Add an asterisk (*) to required field placeholders
            if self.fields[field].required:
                self.fields[field].widget.attrs['placeholder'] += ' *'
