# Generated by Django 3.2.23 on 2024-01-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
